# Generated by Django 4.0.6 on 2024-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solution_feedback_solution_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='teacher_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
